FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime

WORKDIR /lint

COPY api/requirements.txt fastapi_requirements.txt
COPY app/requirements.txt django_requirements.txt

RUN pip install \
    -r fastapi_requirements.txt \
    -r django_requirements.txt \
    pylint

COPY api /fastapi
COPY app /django_demo

CMD ["pylint", "/api/**/*.py"]
