services:

  deno:
    build: ./deno
    volumes:
      - ./django_demo/templates:/templates
      - ./django_demo/static:/static
    env_file: ./.env
    environment:
      - DENO_DIR=/deno
    tty: true

  web:
    build:
      context: ./django_demo
      dockerfile: Dockerfile
    container_name: django_demo
    volumes:
      - ./django_demo:/app    

    ports: 
      - "8050:8050"
    restart: always
    env_file: ./.env


volumes:
  django_templates:
  django_static: