services:
  web:
    build:
      context: ./django_demo
      dockerfile: Dockerfile
    container_name: django_demo
    volumes:
      - type: bind
        source: ./django_demo
        target: /app
    ports: 
      - "8050:8050"
    restart: always
    env_file: ./.env

volumes:
  db_data:
  