[theme]
primaryColor = "#0D7377"  # Темно-сине-зеленый
backgroundColor = "#EAF6F6"  # Светло-голубоватый фон
secondaryBackgroundColor = "#32E0C4"  # Ярко-зеленый
textColor = "#086972"  # Темно-зеленовато-синий текст
font = "sans serif"